name: Auto-Merge-PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Auto-Merge PRs
        uses: MinhOmega/auto-merge@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
